### ISSUE TITLE
Couldn't be found

### ISSUE THREAD

**Issue by abures** [materodev/yii2-bugsnag#1]
When I add to composer.json and run composer update I get this error: The requested package materodev/yii2-bugsnag could not be found in any version, there may be a typo in the package name.

**Comment by MacGyer** [comment]
Did you add 

{
    "type": "vcs",
    "url": "https://github.com/materodev/yii2-bugsnag"
}

to the repositories section of your composer.json?

Side Note: this Yii2 was developed for daily work and our special use cases. Please be aware, that we do not offer any support and the usage in production environment is solely on your liability.

**Comment by abures** [comment]
Ok thank you
